### ISSUE TITLE
Missing compilation procedure in the readme

### ISSUE THREAD

**Issue by yoann-dufresne** [yoann-dufresne/ConwayBromageLib#1]
I tried to compile the code and ended with a missing lest.hpp file.
Because it's a git submodule, I need to do "git submodule init" and "git submodule udate".
Please document it at the beginning of the readme

**Comment by AkumalexTheExalted** [comment]
Added to the documentation
Use the ``--recursive-submodules`` flag during ``git clone`` or ``git submodule init`` and ``git submodule update`` in the project
